//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DE_Laslin4438.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        public int id { get; set; }
        public int order_id { get; set; }
        public int product_id { get; set; }
        public int count { get; set; }
        public System.DateTime order_data { get; set; }
        public System.DateTime delivery_data { get; set; }
        public int checkout_id { get; set; }
        public string status { get; set; }
        public int ver_code { get; set; }
        public int user_id { get; set; }
    
        public virtual Checkout Checkout { get; set; }
        public virtual Products Products { get; set; }
        public virtual Users Users { get; set; }
    }
}
